### ISSUE TITLE
Pretrain Images

### ISSUE THREAD

**Issue by 00Sim** [chan8972/Spike-FlowNet#3]
Hello, thank you for sharing your code and great work.

I am trying to view the results of the pretrained checkpoint_dt1.pth.tar and checkpoint_dt4.pth.tar model on the indoor_flying1

But it seems that the Spike Image and Predicted Flow Output visualizations are very sparse, even with the 4 frame model (results for checkpoint_dt4.pth.tar on indoor_flying1 shown below). 
![PreTrained-4Frames](https://user-images.githubusercontent.com/10778646/96666495-4064d600-1325-11eb-98f2-3a3b454edaed.png)

I am running with the existing parameters in the code:
    batch_size_v = 4, sp_threshold = 0.5

Should any of the parameters be changed to get a denser spike input and thus denser predicted flow output?

**Comment by chan8972** [comment]
-Typically, the spike events are very sparse at the beginning of the video and become denser when the drone starts to fly and roam around the room environments in indoor_flying data. 
-Depending on your computer specs, the code may run slow (taking at most an hour to finish) to test the model and visualize the images/flows. 
-Please set batch_size_v=4 and sp_threshold=0.5 for dt=4 case and batch_size_v=4 and sp_threshold=0.75 for dt=1 case.
-If the problem remains for entire video sequences, please check whether pre-trained models are loaded appropriately.
Thank you for your interest and let me know if this solves your issue.

**Comment by 00Sim** [comment]
Ah got it, the visualizations look as expected later on in the video as the spikes become more dense. Thank you!
