### ISSUE TITLE
selection of sp_threshold=0.875.., Reason?

### ISSUE THREAD

**Issue by ChidanandKumarKS** [chan8972/Spike-FlowNet#7]
@chan8972 
would like to know what is the reason for choosing sp_threshold=0.875 in the line. Kindly help
https://github.com/chan8972/Spike-FlowNet/blob/1061c21d4ee4dda01257db3a533999d8199b0668/main_spike_flow_dt1.py#L249

**Comment by chan8972** [comment]
Thank you for asking this. This is our design choice to set the neuronal firing threshold to 0.75 for dt1 and 0.5 for dt4. Please find more details in our manuscript (https://arxiv.org/pdf/2003.06696.pdf).

**Comment by ChidanandKumarKS** [comment]
Thanks @chan8972 . Closing the issue
